### ISSUE TITLE
Gjøre listen kompatibel med LiteratureRegistry

### ISSUE THREAD

**Issue by Frodeluren** [mknauser/OOP-Gruppe-11#43]

**Comment by Frodeluren** [comment]
Da de blir angitt datatype:
private LiteratureRegistry registry = new LiteratureRegistry();
ObservableList<Book> exampleData = FXCollections.observableArrayList(

Når de legger til data i Listen:
registry.addLiterature(new Book(publisher, title, price, author, edition));
exampleData.add(new Book(publisher, title, price, author, edition));

Printer til listen:
table.setItems(exampleData);

**Comment by mknauser** [comment]
Very nice plannings fRode, keep it up!

**Comment by mknauser** [comment]
https://github.com/mknauser/OOP-Gruppe-11/commit/1aaeee8f43db846055fa44eb06fbf4d0a4daa645
